version: "3"
services:
  backend_server:
    image: ghcr.io/parksujeong74/wonderingpill-back:latest
    restart: "on-failure"
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - wonderingpill_networks
  ai_server:
    image: ghcr.io/kimbyeolhee/wonderingpill-flask:lts
    restart: "always"
    ports:
      - 5001:5001
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -c "cd /app && python /app/app.py -p 5001"
    networks:
      - wonderingpill_networks
  redis:
    image: redis:alpine
    container_name: wondering-redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./data/:/data
      - ./back/conf/redis.conf:/usr/local/conf/redis.conf
    networks:
      - wonderingpill_networks
networks:
  wonderingpill_networks:
    driver: bridge
