version: '3'
services:
  backend_server:
    image: ghcr.io/parksujeong74/wonderingpill-back:latest
    restart: 'on-failure'
    ports:
      - 5000:5000
  redis:
    image: redis:alpine
    container_name: wondering-redis
    volumes:
      - ./docker/volumes/redis:/data
    restart: unless-stopped
    ports:
      - 6379:6379
