version: '3'
services:
  backend_server:
    image: ghcr.io/parksujeong74/wonderingpill-back:latest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - wonderingpill_networks
  redis:
    image: redis:alpine
    container_name: wondering-redis
    ports:
      - 6379:6379
    restart: always
    command: redis-server /usr/local/conf/redis.conf
    volumes:
      - ./:/data
      - ./conf/redis.conf:/usr/local/conf/redis.conf
    networks:
      - wonderingpill_networks
networks:
  wonderingpill_networks:
    driver: bridge
